---

- name: Detect rvm binary
  stat: path='{{ rvm1_rvm }}'
  register: rvm_binary

- name: Detect rvm installer
  stat: path='{{ rvm1_temp_download_path }}/rvm-installer.sh'
  register: rvm_installer

- name: Detect current rvm version
  command: '{{ rvm1_rvm}} version'
  changed_when: False
  register: rvm_current_version
  when: rvm_binary.stat.exists

- name: Install rvm installer
  environment: "{{ proxy_env }}"
  get_url:
    url='{{ rvm1_rvm_latest_installer }}'
    dest='{{ rvm1_temp_download_path }}/rvm-installer.sh'
    validate_certs=no
  when: not rvm_installer.stat.exists

- name: Configure rvm installer
  file:
    path: '{{ rvm1_temp_download_path }}/rvm-installer.sh'
    mode: 0755
  when: not rvm_binary.stat.exists

- name: Import GPG keys
  environment: "{{ proxy_env }}"
  shell: 'curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -'
  changed_when: False
  when: rvm1_gpg_keys != ''
  sudo_user: '{{ rvm1_user }}'
#
# - name: Import pub key
#   environment: "{{ proxy_env }}"
#   shell: 'gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB'
#   sudo_user: '{{ rvm1_user }}'
#   ignore_errors: true

- name: Install rvm
  environment: "{{ proxy_env }}"
  command: >
    {{ rvm1_temp_download_path }}/rvm-installer.sh {{ rvm1_rvm_version }}
    --path {{ rvm1_install_path }} {{ rvm1_install_flags }}
  when: not rvm_binary.stat.exists
  sudo_user: '{{ rvm1_user }}'

- name: Update rvm
  environment: "{{ proxy_env }}"
  shell: '{{ rvm1_rvm }} get {{ rvm1_rvm_version }} && {{ rvm1_rvm }} reload'
  changed_when: False
  when: rvm_binary.stat.exists and rvm1_rvm_check_for_updates
  sudo_user: '{{ rvm1_user }}'
  ignore_errors: true

- name: Configure rvm
  command: '{{ rvm1_rvm }} autolibs {{ rvm1_autolib_mode }}'
  when: not rvm_binary.stat.exists
  sudo_user: '{{ rvm1_user }}'
